version: '3'
services:
  php-fpm:
    build: .
    volumes:
    - /Users/apple/mnmp/site:/usr/share/nginx/html
  nginx:
    image: nginx:stable-alpine
    ports:
    - "80:80"
    volumes:
    - /Users/apple/mnmp/nginx/conf.d:/etc/nginx/conf.d
    - /Users/apple/mnmp/site:/usr/share/nginx/html
    links:
      - php-fpm